name: demo
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - rise
  - ipywidgets
  - scipy
  - xarray
  - plotly
  - requests
  - pip:
    - git+https://github.com/tensorly/tensorly.git
    - wordcloud
    - git+https://github.com/marieroald/component-vis.git